# Generated by Django 6.0.2 on 2026-03-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blogs",
            new_name="Blog",
        ),
    ]
