# Generated by Django 6.0.2 on 2026-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.IntegerField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
