# Generated by Django 6.0.2 on 2026-02-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_category_id_alter_product_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_id",
        ),
    ]
