# Generated by Django 6.0.2 on 2026-02-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_category_category_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="photo",
        ),
    ]
