# Generated by Django 6.0.2 on 2026-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_image_product_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="photo",
            new_name="image",
        ),
    ]
