# Generated by Django 6.0.2 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_photo_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Фото товара"
            ),
        ),
    ]
