# Generated by Django 4.2.2 on 2026-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
